#!/usr/bin/env bash

# Usage: ./build.sh to build pdf and html outputs. ./build.sh clean to remove outputs.

# Assumes that you have programs installed including pdflatex, bibtex, htlatex, and ebook-convert from Calibre.

# If you change the name of your main TeX source file, change this variable to the new name.
MAINFILE=ebookbook
AUTHOR="Dominic Widdows" # Of course, you'll want to change this.

# This is the main build process, from running "./build.sh".
if [[ $# -eq 0 ]]
   then
	pdflatex $MAINFILE
	bibtex $MAINFILE
	pdflatex $MAINFILE
	pdflatex $MAINFILE

	htlatex $MAINFILE.tex "xhtml,fn-in"

	ebook-convert ebookbook.html ebookbook.epub --cover images/cover.jpg --authors "$AUTHOR" --language English --mobi-file-type new
	ebook-convert ebookbook.html ebookbook.mobi --cover images/cover.jpg --authors "$AUTHOR" --language English --mobi-file-type new

# This is the build cleanup process, from running "./build.sh clean".
# It removes all the output files known to be generated by pdflatex and htlatex.	
elif [[ $# -eq 1 ]] && [[ $1 == "clean" ]]
    then
	for extension in 4ct 4tc aux bbl blg css dvi epub kpf html idv lg log mobi out pdf ps tmp toc xref; do \
	    for file in "$MAINFILE"*."$extension"; do \
		echo "Removing output file $file";
		rm $file;
	    done;
	done

else
    echo Arguments not recognized: $@
    echo Usage: ./build.sh to build pdf, html, epub and mobi outputs.
    echo ./build.sh clean to remove outputs.
fi
